/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminTabletModeRouteImport } from './routes/admin/tablet-mode'
import { Route as ApiPublicPushRemindersRouteImport } from './routes/api/public/push/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTabletModeRoute = AdminTabletModeRouteImport.update({
  id: '/tablet-mode',
  path: '/tablet-mode',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPushRemindersRoute = ApiPublicPushRemindersRouteImport.update({
  id: '/api/public/push/reminders',
  path: '/api/public/push/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/engagement': typeof EngagementRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/tablet-mode': typeof AdminTabletModeRoute
  '/api/public/push/reminders': typeof ApiPublicPushRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/engagement': typeof EngagementRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/tablet-mode': typeof AdminTabletModeRoute
  '/api/public/push/reminders': typeof ApiPublicPushRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/engagement': typeof EngagementRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/tablet-mode': typeof AdminTabletModeRoute
  '/api/public/push/reminders': typeof ApiPublicPushRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/engagement'
    | '/login'
    | '/reset-password'
    | '/super-admin'
    | '/admin/services'
    | '/admin/tablet-mode'
    | '/api/public/push/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/engagement'
    | '/login'
    | '/reset-password'
    | '/super-admin'
    | '/admin/services'
    | '/admin/tablet-mode'
    | '/api/public/push/reminders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/engagement'
    | '/login'
    | '/reset-password'
    | '/super-admin'
    | '/admin/services'
    | '/admin/tablet-mode'
    | '/api/public/push/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EngagementRoute: typeof EngagementRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuperAdminRoute: typeof SuperAdminRoute
  ApiPublicPushRemindersRoute: typeof ApiPublicPushRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tablet-mode': {
      id: '/admin/tablet-mode'
      path: '/tablet-mode'
      fullPath: '/admin/tablet-mode'
      preLoaderRoute: typeof AdminTabletModeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/push/reminders': {
      id: '/api/public/push/reminders'
      path: '/api/public/push/reminders'
      fullPath: '/api/public/push/reminders'
      preLoaderRoute: typeof ApiPublicPushRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminServicesRoute: typeof AdminServicesRoute
  AdminTabletModeRoute: typeof AdminTabletModeRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminServicesRoute: AdminServicesRoute,
  AdminTabletModeRoute: AdminTabletModeRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EngagementRoute: EngagementRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuperAdminRoute: SuperAdminRoute,
  ApiPublicPushRemindersRoute: ApiPublicPushRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
